# Generated by Django 5.1.6 on 2025-02-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Name',
            new_name='restaurant',
        ),
    ]
